"""added an album

Revision ID: 04ff205b0590
Revises: 7779e858a92a
Create Date: 2023-04-07 15:20:59.105026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ff205b0590'
down_revision = '7779e858a92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['member.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums')
    # ### end Alembic commands ###
