"""not sure tbh

Revision ID: 3fca2812f5f4
Revises: 3988632a79da
Create Date: 2023-04-05 15:58:17.290982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fca2812f5f4'
down_revision = '3988632a79da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('hometown', sa.VARCHAR(length=128), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=1), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
